FROM wdps_spark_base:v1

CMD bash

#FROM bde2020/spark-python-template:2.4.4-hadoop2.7
#
#RUN apk update
#RUN apk add make automake gcc g++ subversion python3-dev libxml2 libxml2-dev
## hotfix to install backend deps.
#RUN pip3 install spacy==2.2.2